CREATE DATABASE IF NOT EXISTS rabbit_app DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE rabbit_app;

CREATE TABLE IF NOT EXISTS sys_user (
  user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  password_initialized BOOLEAN NOT NULL DEFAULT TRUE,
  openid VARCHAR(128),
  phone_country_code VARCHAR(8),
  phone_hash CHAR(64),
  phone_masked VARCHAR(32),
  phone_bound_time DATETIME,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_user_openid (openid),
  UNIQUE KEY uk_sys_user_phone_hash (phone_hash),
  KEY idx_sys_user_status (status, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS platform_admins (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'SUPER_ADMIN',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_time DATETIME,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_platform_admin_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabbit_houses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  name VARCHAR(100) NOT NULL,
  layout_rows INT NOT NULL DEFAULT 0,
  layout_cols INT NOT NULL DEFAULT 0,
  layout_layers INT NOT NULL DEFAULT 0,
  request_id VARCHAR(64),
  remark TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_house_creator_req (create_by, request_id),
  KEY idx_rabbit_houses_status (status, is_deleted, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS house_users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'VIEWER',
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  perms VARCHAR(10) NOT NULL DEFAULT 'view',
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  join_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_house_user (house_id, user_id),
  KEY idx_user_id (user_id),
  KEY idx_house_users_user_house (user_id, house_id),
  KEY idx_house_users_house_role (house_id, role, user_id),
  KEY idx_house_users_user_status (user_id, status, house_id),
  CONSTRAINT fk_house_users_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_house_users_user FOREIGN KEY (user_id) REFERENCES sys_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS house_invitations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  phone_hash CHAR(64) NOT NULL,
  phone_masked VARCHAR(32) NOT NULL,
  role VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  request_id VARCHAR(64) NOT NULL,
  invited_by_user_id BIGINT NOT NULL,
  accepted_user_id BIGINT,
  expires_time DATETIME NOT NULL,
  accepted_time DATETIME,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_house_invitations_request (house_id, invited_by_user_id, request_id),
  KEY idx_house_invitations_house_phone_status (house_id, phone_hash, status, id),
  KEY idx_house_invitations_phone_status_expiry (phone_hash, status, expires_time),
  KEY idx_house_invitations_inviter (invited_by_user_id, status, house_id),
  KEY idx_house_invitations_accepted_user (accepted_user_id, status, house_id),
  CONSTRAINT fk_house_invitations_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_house_invitations_inviter FOREIGN KEY (invited_by_user_id) REFERENCES sys_user (user_id),
  CONSTRAINT fk_house_invitations_accepted_user FOREIGN KEY (accepted_user_id) REFERENCES sys_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  cage_number VARCHAR(50) NOT NULL,
  row_code VARCHAR(40),
  layer_index INT,
  position_index INT,
  status VARCHAR(1) NOT NULL DEFAULT '0',
  rabbit_count INT NOT NULL DEFAULT 0,
  is_fed BOOLEAN NOT NULL DEFAULT FALSE,
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_house_cage_number (house_id, cage_number),
  KEY idx_house_id (house_id),
  KEY idx_cages_house_row_position (house_id, row_code, position_index, layer_index),
  CONSTRAINT fk_cages_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cage_nfc_tags (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  cage_id BIGINT NOT NULL,
  tag_uid VARCHAR(40) NOT NULL,
  request_id VARCHAR(64),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cage_nfc_uid (house_id, tag_uid),
  UNIQUE KEY uk_cage_nfc_cage (house_id, cage_id),
  KEY idx_cage_nfc_house (house_id),
  KEY idx_cage_nfc_cage (cage_id),
  CONSTRAINT fk_cage_nfc_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_cage_nfc_cage FOREIGN KEY (cage_id) REFERENCES cages (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfc_tags (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  tag_uid VARCHAR(40) NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  target_id BIGINT,
  rabbit_id BIGINT,
  record_id BIGINT,
  request_id VARCHAR(64),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_nfc_uid (house_id, tag_uid),
  UNIQUE KEY uk_nfc_target (house_id, target_type, target_id),
  KEY idx_nfc_house (house_id),
  KEY idx_nfc_target (target_type, target_id),
  CONSTRAINT fk_nfc_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS global_setting (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  user_id BIGINT,
  aphrodisiac_days INT NOT NULL,
  palpation_days INT NOT NULL,
  prepartum_days INT NOT NULL,
  weaning_days INT NOT NULL,
  postpartum_days INT NOT NULL,
  sale_days INT NOT NULL,
  replacement_days INT NOT NULL,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_setting_house (house_id),
  UNIQUE KEY uk_setting_user (user_id),
  CONSTRAINT fk_setting_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_setting_user FOREIGN KEY (user_id) REFERENCES sys_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabbits (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  cage_id BIGINT NOT NULL,
  mother_id BIGINT,
  father_id BIGINT,
  birth_batch_id BIGINT,
  birth_cycle_id BIGINT,
  type VARCHAR(1) NOT NULL,
  gender VARCHAR(1) NOT NULL,
  breed VARCHAR(100),
  arrival_method VARCHAR(1),
  arrival_date DATETIME,
  weight DOUBLE,
  growth_stage VARCHAR(20),
  reproductive_stage VARCHAR(20),
  current_stage VARCHAR(20),
  current_cycle_id BIGINT,
  stage_entered_at DATETIME,
  last_mating_date DATETIME,
  state_version BIGINT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  active_breeding_cage_id BIGINT GENERATED ALWAYS AS (
    CASE WHEN is_active = TRUE AND type IN ('0', '1') THEN cage_id ELSE NULL END
  ) STORED,
  is_quarantined BOOLEAN NOT NULL DEFAULT FALSE,
  quarantine_time DATETIME,
  quarantine_reason VARCHAR(200),
  request_id VARCHAR(64),
  departure_date DATETIME,
  departure_reason VARCHAR(20),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_rabbits_house_id (house_id),
  KEY idx_rabbits_cage_id (cage_id),
  KEY idx_rabbits_house_cage_active_type_id (house_id, cage_id, is_active, type, id),
  KEY idx_rabbits_father (father_id),
  KEY idx_rabbits_birth_cycle (birth_cycle_id),
  KEY idx_rabbits_house_birth_batch_id (house_id, birth_batch_id, id),
  KEY idx_rabbits_house_current_stage (house_id, current_stage, id),
  KEY idx_rabbits_active (is_active),
  KEY idx_rabbits_quarantined (is_quarantined),
  UNIQUE KEY uk_rabbit_req (house_id, request_id),
  UNIQUE KEY uk_rabbits_house_active_breeding_cage (house_id, active_breeding_cage_id),
  CONSTRAINT fk_rabbits_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_rabbits_cage FOREIGN KEY (cage_id) REFERENCES cages (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabbit_departure_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  request_id VARCHAR(64),
  departure_type VARCHAR(20) NOT NULL,
  departure_date DATETIME NOT NULL,
  reason VARCHAR(200),
  remark TEXT,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_departure_req (house_id, rabbit_id, request_id),
  KEY idx_departure_house_time (house_id, departure_date),
  KEY idx_departure_rabbit (rabbit_id),
  CONSTRAINT fk_departure_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_departure_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS batches (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  batch_code VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '进行中',
  start_date DATETIME,
  end_date DATETIME,
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  request_id VARCHAR(64),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_batches_house_id (house_id),
  KEY idx_batches_status (status),
  UNIQUE KEY uk_batch_req (house_id, request_id),
  CONSTRAINT fk_batches_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS breeding_cycles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT,
  house_id BIGINT NOT NULL,
  -- V26 起可空：散养母兔不归属任何批次（业务裁定 2026-08-16）。
  batch_id BIGINT,
  mother_rabbit_id BIGINT NOT NULL,
  male_rabbit_id BIGINT,
  cycle_no INT NOT NULL,
  -- 中文 status 镜像列已随 V28 删除：一个 stage 可能对应多个旧状态值
  -- （待备产与待分娩都写「怀孕确认」），它从来不是可靠判据。
  -- 权威状态是 stage + lifecycle + result。
  stage VARCHAR(20) NOT NULL,
  stage_entered_at DATETIME NOT NULL,
  lifecycle VARCHAR(10) NOT NULL DEFAULT 'OPEN',
  result VARCHAR(10),
  mating_method VARCHAR(10),
  state_version BIGINT NOT NULL DEFAULT 0,
  pipeline_guard BIGINT GENERATED ALWAYS AS (
    CASE WHEN lifecycle = 'OPEN'
          AND stage IN ('AWAIT_ESTRUS', 'AWAIT_MATING', 'AWAIT_PALPATION',
                        'AWAIT_PREPARTUM', 'AWAIT_DELIVERY')
         THEN mother_rabbit_id END
  ) STORED,
  -- batch_member_guard 已随 V28 删除：V27 最终没有创建 uk_bc_batch_member
  -- （它会连哺乳周期一起算，反而挡掉 pipeline_guard 特意允许的血配）。
  mating_date DATETIME,
  pregnancy_check_date DATETIME,
  pregnancy_result VARCHAR(10),
  expected_birth_date DATETIME,
  birth_date DATETIME,
  total_kits INT NOT NULL DEFAULT 0,
  live_kits INT NOT NULL DEFAULT 0,
  foster_in_kits INT NOT NULL DEFAULT 0,
  foster_out_kits INT NOT NULL DEFAULT 0,
  current_nursing_kits INT NOT NULL DEFAULT 0,
  weaned_kits INT NOT NULL DEFAULT 0,
  preweaning_loss_kits INT NOT NULL DEFAULT 0,
  weaning_date DATETIME,
  avg_weaning_weight DOUBLE,
  lactation_days INT,
  -- V28 删除：overlap_* 是只写不读的死数据（血配改用「两条并存的开放周期」表达）；
  -- next_event_* / is_event_notified / event_notify_date 的职责已整体迁到 work_tasks。
  closed_at DATETIME,
  close_reason VARCHAR(100),
  request_id VARCHAR(64),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_bc_batch_mother_cycle (house_id, batch_id, mother_rabbit_id, cycle_no),
  UNIQUE KEY uk_bc_request (house_id, request_id),
  -- 一只母兔同时只能有一个在途管线周期（V27 起生效）。
  -- 对旧写路径行为中性：旧代码不写 stage → pipeline_guard 为 NULL → 唯一键不约束。
  -- 注意没有配套的 uk_bc_batch_member：它会连同批次内的血配一起挡死，
  -- 且 pipeline_guard 的保证范围本就更严。理由详见 V27 迁移文件。
  UNIQUE KEY uk_bc_pipeline (house_id, pipeline_guard),
  KEY idx_bc_status (house_id, status, closed_at),
  KEY idx_bc_stage (house_id, lifecycle, stage, id),
  KEY idx_bc_mother_lifecycle (house_id, mother_rabbit_id, lifecycle, id),
  KEY idx_bc_next_event (house_id, next_event_date, is_event_notified),
  CONSTRAINT fk_bc_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_bc_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_bc_mother FOREIGN KEY (mother_rabbit_id) REFERENCES rabbits (id),
  CONSTRAINT fk_bc_male FOREIGN KEY (male_rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS batch_rabbits (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  male_rabbit_id BIGINT,
  latest_cycle_id BIGINT,
  current_nursing_kits INT NOT NULL DEFAULT 0,
  nursing_litter_count INT NOT NULL DEFAULT 0,
  join_reason VARCHAR(20) NOT NULL,
  batch_role VARCHAR(20) NOT NULL,
  current_status VARCHAR(30) NOT NULL,
  last_event_date DATETIME,
  next_event_date DATETIME,
  next_event_type VARCHAR(30),
  is_event_notified BOOLEAN NOT NULL DEFAULT FALSE,
  event_notify_date DATETIME,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  join_date DATETIME NOT NULL,
  exit_date DATETIME,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_batch_rabbits_batch (batch_id),
  KEY idx_batch_rabbits_rabbit (rabbit_id),
  KEY idx_br_latest_cycle (latest_cycle_id),
  KEY idx_batch_rabbits_next_event (next_event_date, next_event_type),
  KEY idx_batch_rabbits_active (is_active),
  CONSTRAINT fk_batch_rabbits_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_batch_rabbits_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pregnancy_check_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  batch_id BIGINT NOT NULL,
  breeding_cycle_id BIGINT,
  rabbit_id BIGINT NOT NULL,
  check_date DATETIME NOT NULL,
  result VARCHAR(10) NOT NULL,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pcr_house_batch (house_id, batch_id, id),
  KEY idx_pcr_house_rabbit (house_id, rabbit_id, id),
  KEY idx_pcr_cycle (breeding_cycle_id),
  KEY idx_pcr_batch (batch_id),
  KEY idx_pcr_rabbit (rabbit_id),
  CONSTRAINT fk_pcr_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_pcr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parturition_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  batch_id BIGINT NOT NULL,
  breeding_cycle_id BIGINT,
  rabbit_id BIGINT NOT NULL,
  birth_date DATETIME NOT NULL,
  total_kits INT NOT NULL DEFAULT 0,
  live_kits INT NOT NULL DEFAULT 0,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pr_house_batch (house_id, batch_id, id),
  KEY idx_pr_house_rabbit (house_id, rabbit_id, id),
  KEY idx_pr_house_birth_id (house_id, birth_date, id),
  KEY idx_pr_cycle (breeding_cycle_id),
  KEY idx_pr_batch (batch_id),
  KEY idx_pr_rabbit (rabbit_id),
  CONSTRAINT fk_pr_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_pr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prepartum_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  batch_id BIGINT NOT NULL,
  breeding_cycle_id BIGINT,
  rabbit_id BIGINT NOT NULL,
  action_date DATETIME NOT NULL,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ppr_house_batch (house_id, batch_id, id),
  KEY idx_ppr_house_rabbit (house_id, rabbit_id, id),
  KEY idx_ppr_cycle (breeding_cycle_id),
  KEY idx_ppr_batch (batch_id),
  KEY idx_ppr_rabbit (rabbit_id),
  CONSTRAINT fk_ppr_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_ppr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS weaning_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  -- V29 放开非空：散养母兔没有批次，分笼记录归属的是窝与周期
  batch_id BIGINT,
  breeding_cycle_id BIGINT,
  rabbit_id BIGINT NOT NULL,
  target_cage_id BIGINT,
  in_cage_id BIGINT,
  weaning_date DATETIME,
  weaning_count INT NOT NULL,
  waiting_count INT NOT NULL DEFAULT 0,
  male_count INT,
  female_count INT,
  avg_weight DOUBLE,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_wr_house_batch (house_id, batch_id, id),
  KEY idx_wr_house_rabbit (house_id, rabbit_id, id),
  KEY idx_wr_house_weaning_id (house_id, weaning_date, id),
  KEY idx_wr_cycle (breeding_cycle_id),
  KEY idx_wr_batch (batch_id),
  KEY idx_wr_rabbit (rabbit_id),
  KEY idx_wr_target_cage (target_cage_id),
  KEY idx_wr_in_cage (in_cage_id),
  CONSTRAINT fk_wr_batch FOREIGN KEY (batch_id) REFERENCES batches (id),
  CONSTRAINT fk_wr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS weaning_record_allocations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  weaning_record_id BIGINT NOT NULL,
  cage_id BIGINT NOT NULL,
  alloc_count INT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_wra_record_cage (weaning_record_id, cage_id),
  KEY idx_wra_record (weaning_record_id),
  KEY idx_wra_cage (cage_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS feed_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  item_id BIGINT,
  feeding_rabbits VARCHAR(300),
  feed_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  feed_type VARCHAR(100),
  unit VARCHAR(20),
  request_id VARCHAR(64),
  amount DECIMAL(10,2) NOT NULL,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_feed_house (house_id),
  KEY idx_feed_time (feed_time),
  KEY idx_feed_item (item_id),
  CONSTRAINT fk_feed_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS feed_log_rabbits (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  feed_log_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  cage_id BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_flr (feed_log_id, rabbit_id),
  KEY idx_flr_house_cage (house_id, cage_id, feed_log_id),
  KEY idx_flr_rabbit (rabbit_id),
  CONSTRAINT fk_flr_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_flr_feed FOREIGN KEY (feed_log_id) REFERENCES feed_logs (id),
  CONSTRAINT fk_flr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  unit VARCHAR(20) NOT NULL,
  current_qty DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  low_stock_qty DECIMAL(12,3),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_inv_item (house_id, name),
  KEY idx_inv_house (house_id),
  CONSTRAINT fk_inv_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory_txs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  item_id BIGINT NOT NULL,
  tx_type VARCHAR(20) NOT NULL,
  qty_delta DECIMAL(12,3) NOT NULL,
  tx_time DATETIME NOT NULL,
  ref_table VARCHAR(100),
  ref_id BIGINT,
  remark TEXT,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_inv_tx_house_time (house_id, tx_time),
  KEY idx_inv_tx_item (item_id, tx_time),
  UNIQUE KEY uk_inv_tx_req (house_id, item_id, request_id),
  CONSTRAINT fk_inv_tx_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_inv_tx_item FOREIGN KEY (item_id) REFERENCES inventory_items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabbit_status_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT,
  rabbit_id BIGINT NOT NULL,
  batch_id BIGINT,
  from_status VARCHAR(50),
  to_status VARCHAR(50) NOT NULL,
  change_time DATETIME NOT NULL,
  reason VARCHAR(255),
  related_record_id BIGINT,
  related_record_table VARCHAR(100),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_rsh_house_rabbit_time (house_id, rabbit_id, change_time, id),
  KEY idx_rsh_house_batch_time (house_id, batch_id, change_time, id),
  KEY idx_rsh_rabbit (rabbit_id),
  KEY idx_rsh_batch (batch_id),
  KEY idx_rsh_time (change_time),
  CONSTRAINT fk_rsh_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabbit_abnormal_conditions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  rabbit_id BIGINT NOT NULL,
  house_id BIGINT NOT NULL,
  warning_status VARCHAR(50),
  warning_time DATETIME,
  img_url VARCHAR(255),
  remark VARCHAR(255),
  is_deal BOOLEAN DEFAULT FALSE,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_rac_house (house_id),
  KEY idx_rac_rabbit (rabbit_id),
  KEY idx_rac_house_rabbit_deal (house_id, rabbit_id, is_deal),
  CONSTRAINT fk_rac_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_rac_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS treatment_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  start_date DATETIME NOT NULL,
  diagnosis VARCHAR(200),
  drug VARCHAR(200),
  dose VARCHAR(100),
  days INT,
  next_review_date DATETIME,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  remark TEXT,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tr_req (house_id, rabbit_id, request_id),
  KEY idx_tr_house_review (house_id, next_review_date, status),
  KEY idx_tr_rabbit (rabbit_id),
  CONSTRAINT fk_tr_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_tr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS weight_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  weigh_time DATETIME NOT NULL,
  weight_kg DOUBLE NOT NULL,
  remark TEXT,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_wl_req (house_id, rabbit_id, request_id),
  KEY idx_wl_house_time (house_id, weigh_time),
  KEY idx_wl_rabbit (rabbit_id),
  CONSTRAINT fk_wl_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_wl_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sale_orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  sale_time DATETIME NOT NULL,
  customer VARCHAR(100),
  total_weight DOUBLE NOT NULL,
  unit_price DECIMAL(10,2),
  total_amount DECIMAL(12,2),
  remark TEXT,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sale_req (house_id, request_id),
  KEY idx_sale_house_time (house_id, sale_time),
  CONSTRAINT fk_sale_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sale_order_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  sale_order_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  cage_id_snapshot BIGINT,
  cage_number_snapshot VARCHAR(50),
  row_code_snapshot VARCHAR(40),
  layer_index_snapshot INT,
  position_index_snapshot INT,
  rabbit_type_snapshot VARCHAR(1),
  stage_snapshot VARCHAR(30),
  parallel_status_snapshot VARCHAR(120),
  state_version_snapshot BIGINT,
  early_sale BOOLEAN NOT NULL DEFAULT FALSE,
  early_sale_reason VARCHAR(300),
  batch_id_snapshot BIGINT,
  weight DOUBLE,
  price DECIMAL(10,2),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_soi_order (sale_order_id),
  KEY idx_soi_rabbit (rabbit_id),
  UNIQUE KEY uk_sale_order_rabbit (sale_order_id, rabbit_id),
  CONSTRAINT fk_soi_order FOREIGN KEY (sale_order_id) REFERENCES sale_orders (id),
  CONSTRAINT fk_soi_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outbound_tasks (
  task_id VARCHAR(36) PRIMARY KEY,
  house_id BIGINT NOT NULL,
  operator_id BIGINT NOT NULL,
  entry_type VARCHAR(16) NOT NULL,
  source_rabbit_id BIGINT,
  source_cage_id BIGINT,
  source_row_code VARCHAR(40),
  status VARCHAR(24) NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0,
  sale_time DATETIME,
  total_weight DOUBLE,
  unit_price DECIMAL(10,2),
  customer VARCHAR(100),
  remark TEXT,
  request_id VARCHAR(64),
  sale_order_id BIGINT,
  snapshot_time DATETIME,
  completed_time DATETIME,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_outbound_task_house_operator (house_id, operator_id, status, update_time),
  KEY idx_outbound_task_sale_order (sale_order_id),
  CONSTRAINT fk_outbound_task_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_outbound_task_operator FOREIGN KEY (operator_id) REFERENCES sys_user (user_id),
  CONSTRAINT fk_outbound_task_sale_order FOREIGN KEY (sale_order_id) REFERENCES sale_orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outbound_task_items (
  task_id VARCHAR(36) NOT NULL,
  rabbit_id BIGINT NOT NULL,
  state_version BIGINT NOT NULL,
  selection_type VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
  early_sale_reason VARCHAR(300),
  cage_id_snapshot BIGINT NOT NULL,
  cage_number_snapshot VARCHAR(50) NOT NULL,
  row_code_snapshot VARCHAR(40) NOT NULL,
  layer_index_snapshot INT,
  position_index_snapshot INT,
  stage_snapshot VARCHAR(30),
  batch_id_snapshot BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (task_id, rabbit_id),
  KEY idx_outbound_item_rabbit (rabbit_id),
  CONSTRAINT fk_outbound_item_task FOREIGN KEY (task_id) REFERENCES outbound_tasks (task_id),
  CONSTRAINT fk_outbound_item_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outbound_requests (
  request_id VARCHAR(64) PRIMARY KEY,
  house_id BIGINT NOT NULL,
  task_id VARCHAR(36) NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL,
  sale_order_id BIGINT,
  error_code VARCHAR(64),
  error_message VARCHAR(500),
  conflicts_json MEDIUMTEXT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_outbound_request_task (task_id, update_time),
  KEY idx_outbound_request_sale_order (sale_order_id),
  CONSTRAINT fk_outbound_request_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_outbound_request_task FOREIGN KEY (task_id) REFERENCES outbound_tasks (task_id),
  CONSTRAINT fk_outbound_request_sale_order FOREIGN KEY (sale_order_id) REFERENCES sale_orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS breeding_performance (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  total_litters INT NOT NULL DEFAULT 0,
  total_kits INT NOT NULL DEFAULT 0,
  total_live_kits INT NOT NULL DEFAULT 0,
  total_weaned INT NOT NULL DEFAULT 0,
  success_breeding_count INT NOT NULL DEFAULT 0,
  failed_breeding_count INT NOT NULL DEFAULT 0,
  avg_litter_size DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  avg_weaning_size DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  last_litter_date DATETIME,
  performance_score INT,
  remark TEXT,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_bp_house_rabbit (house_id, rabbit_id),
  KEY idx_bp_house (house_id),
  CONSTRAINT fk_bp_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_bp_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS replacement_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  rabbit_id BIGINT NOT NULL,
  original_type VARCHAR(1) NOT NULL DEFAULT '2',
  replacement_date DATETIME NOT NULL,
  expected_mature_date DATETIME NOT NULL,
  is_mature_notified BOOLEAN DEFAULT FALSE,
  mature_notify_date DATETIME,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_rr_house (house_id),
  KEY idx_rr_expected (expected_mature_date),
  UNIQUE KEY uk_replacement_house_request_rabbit (house_id, request_id, rabbit_id),
  CONSTRAINT fk_rr_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_rr_rabbit FOREIGN KEY (rabbit_id) REFERENCES rabbits (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_acks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  category VARCHAR(32) NOT NULL,
  record_id BIGINT NOT NULL,
  action VARCHAR(16) NOT NULL,
  snooze_until DATETIME,
  ack_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(255),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_event_ack_user_cat_record (user_id, category, record_id),
  KEY idx_event_ack_house (house_id),
  KEY idx_event_ack_snooze (snooze_until),
  CONSTRAINT fk_event_ack_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id),
  CONSTRAINT fk_event_ack_user FOREIGN KEY (user_id) REFERENCES sys_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS request_dedup (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  api VARCHAR(64) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  payload_hash VARCHAR(64) NULL,
  status VARCHAR(16) NOT NULL,
  error_message VARCHAR(255),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_request_dedup (house_id, user_id, api, request_id),
  KEY idx_request_dedup_house (house_id),
  KEY idx_request_dedup_user (user_id),
  KEY idx_request_dedup_update (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS phone_one_tap_attempts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(64) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  request_ip VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  lease_id VARCHAR(64) NOT NULL,
  lease_expires_time DATETIME(3),
  response_code INT,
  response_message VARCHAR(128),
  user_id BIGINT,
  success_time DATETIME(3),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_phone_one_tap_request_id (request_id),
  UNIQUE KEY uk_phone_one_tap_token_hash (token_hash),
  KEY idx_phone_one_tap_ip_time (request_ip, create_time),
  KEY idx_phone_one_tap_status_time (status, update_time),
  KEY idx_phone_one_tap_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS phone_one_tap_rate_buckets (
  request_ip VARCHAR(64) NOT NULL,
  bucket_type VARCHAR(16) NOT NULL,
  bucket_start DATETIME NOT NULL,
  request_count INT NOT NULL DEFAULT 0,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (request_ip, bucket_type, bucket_start),
  KEY idx_phone_one_tap_bucket_start (bucket_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trace_id VARCHAR(64),
  user_id BIGINT,
  house_id BIGINT,
  method VARCHAR(10),
  path VARCHAR(255),
  query_string VARCHAR(1000),
  status INT,
  api_code INT,
  api_message VARCHAR(255),
  cost_ms BIGINT,
  error_message VARCHAR(500),
  ip VARCHAR(64),
  user_agent VARCHAR(255),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_audit_house_time (house_id, create_time),
  KEY idx_audit_house_id (house_id, id),
  KEY idx_audit_user_time (user_id, create_time),
  KEY idx_audit_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_reminder_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_id BIGINT NOT NULL,
  category VARCHAR(32) NOT NULL,
  record_id BIGINT NOT NULL,
  event_date DATETIME,
  notify_date DATE NOT NULL,
  notify_time DATETIME NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_erl_house_cat_record_date (house_id, category, record_id, notify_date),
  KEY idx_erl_house_date_id (house_id, notify_date, id),
  CONSTRAINT fk_erl_house FOREIGN KEY (house_id) REFERENCES rabbit_houses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 母兔生产流程 V2（V26 起）：事件流 / 窝 / 统一任务中心 / 通用附件
CREATE TABLE IF NOT EXISTS repro_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT,
  house_id BIGINT NOT NULL,
  cycle_id BIGINT,
  litter_id BIGINT,
  mother_rabbit_id BIGINT NOT NULL,
  batch_id BIGINT,
  event_type VARCHAR(32) NOT NULL,
  from_stage VARCHAR(20),
  to_stage VARCHAR(20),
  occurred_at DATETIME NOT NULL,
  payload JSON,
  operator_id BIGINT,
  operator_name VARCHAR(64) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_re_request (house_id, request_id),
  KEY idx_re_cycle (house_id, cycle_id, id),
  KEY idx_re_mother_time (house_id, mother_rabbit_id, occurred_at),
  KEY idx_re_house_time (house_id, occurred_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS litters (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT,
  house_id BIGINT NOT NULL,
  cycle_id BIGINT NOT NULL,
  mother_rabbit_id BIGINT NOT NULL,
  sire_rabbit_id BIGINT,
  batch_id BIGINT,
  birth_date DATETIME NOT NULL,
  total_kits INT NOT NULL,
  live_kits INT NOT NULL,
  kept_kits INT NOT NULL,
  foster_in INT NOT NULL DEFAULT 0,
  foster_out INT NOT NULL DEFAULT 0,
  loss_count INT NOT NULL DEFAULT 0,
  current_nursing INT NOT NULL DEFAULT 0,
  status VARCHAR(10) NOT NULL,
  weaning_date DATETIME,
  weaned_count INT,
  avg_weaning_weight DOUBLE,
  nursing_cage_id BIGINT,
  request_id VARCHAR(64),
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_lt_cycle (house_id, cycle_id),
  KEY idx_lt_status (house_id, status, birth_date),
  KEY idx_lt_mother (house_id, mother_rabbit_id, birth_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS work_tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT,
  house_id BIGINT NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  subject_type VARCHAR(16) NOT NULL,
  subject_id BIGINT NOT NULL,
  cycle_id BIGINT,
  rabbit_id BIGINT,
  batch_id BIGINT,
  cage_id BIGINT,
  due_date DATE NOT NULL,
  due_time DATETIME NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'PENDING',
  snooze_count INT NOT NULL DEFAULT 0,
  completed_event_id BIGINT,
  dedup_key VARCHAR(96) NOT NULL,
  remark TEXT,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_wt_dedup (house_id, dedup_key),
  KEY idx_wt_due (house_id, status, due_date, task_type),
  KEY idx_wt_subject (house_id, subject_type, subject_id, status),
  KEY idx_wt_cage (house_id, cage_id, status),
  KEY idx_wt_batch (house_id, batch_id, status, task_type),
  KEY idx_wt_rabbit (house_id, rabbit_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_attachments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT,
  house_id BIGINT NOT NULL,
  biz_type VARCHAR(32) NOT NULL,
  biz_id BIGINT NOT NULL,
  file_id VARCHAR(128) NOT NULL,
  file_name VARCHAR(255),
  content_type VARCHAR(100),
  file_size BIGINT,
  sort_no INT NOT NULL DEFAULT 0,
  request_id VARCHAR(64),
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ba_biz_file (house_id, biz_type, biz_id, file_id),
  KEY idx_ba_biz (house_id, biz_type, biz_id, sort_no, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS business_files (
  id VARCHAR(64) PRIMARY KEY,
  house_id BIGINT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL,
  sha256 CHAR(64) NOT NULL,
  content LONGBLOB NOT NULL,
  create_by VARCHAR(64),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_business_files_house_sha (house_id, sha256),
  KEY idx_business_files_house_created (house_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
